### ISSUE TITLE
Store auth rules in GitHub

### ISSUE THREAD

**Issue by asim** [micro/development#114]
Our auth rules basically exist in one place, live. Auth rules should be stored in github so we can apply them when booting all the services. For now we should store them in one place micro/services/auth/rules and then they can be applied programattically.

**Comment by ben-toogood** [comment]
I'll write a small service which periodically pulls this file and checks to ensure it's consistent with what's configured in the auth service. I know this is a small thing to be a service but since we have no auth services in micro/services I think this is better than adding it into something like account web service for instance.

**Comment by asim** [comment]
If you write the rules in a config file along side this service it won't need to poll github, every time the rules are changed it will trigger a redeploy and they can be inserted into the micro auth service

**Comment by ben-toogood** [comment]
Good idea 👍
