### ISSUE TITLE
web.home resolver

### ISSUE THREAD

**Issue by ben-toogood** [micro/development#124]
if you find the service "[namespace].web.home" serve it instead of web and where you see web.[namespace] subdomain ensure web is served there

5:49
assumption would be micro.mu is served by home app. web.micro.mu serves web itself

**Comment by ben-toogood** [comment]
@asim shall we refactor micro web as part of this as discussed yesterday?

**Comment by asim** [comment]
Yea I think this makes sense. It will drastically simplify things. 

A few parts:
- micro web is a built in "home"
- micro web can be explicitly retrieved via "web + namespace" e.g web.micro.mu or /web
- when we find a home web app it replaces what's served at / and the naked domain e.g micro.mu
- when /[service] is found as a web app we route to it

**Comment by ben-toogood** [comment]
A couple of questions:
• It makes sense for the default "home" (micro web) to be registered as a standalone service, what do we name this service? "[namespace].web.home.default"? 
• If the /web app is requested, and a "[namespace].web.home" is present (a custom home app), do we serve the default web app or the custom one?

**Comment by asim** [comment]
- I would not register this service, because how do you then know that a replacement exists? I think its a built in fallback. Micro web is basically displaying a service directory listing where no home web app exists. It's just built in, it's not run separately.

- Maybe for now /web is a reserved path? And we always serve the web app? It might mean that something like kytra.m3o.app serves the home app where it exists but the user always knows they can go to kytra.m3o.app/web for the admin rather than web.kytra.m3o.app.

**Comment by ben-toogood** [comment]
Regarding your first point, if we use "go.micro.web.home.**default**", this will be a different name to the normal home. I just think the more we can treat it like any other service, the cleaner the web code will be, since we can just proxy to the service? No hacky logic to determine if we should proxy or not.

**Comment by asim** [comment]
its not hacky logic, its just logic. As in:

1. select home from registry
2. found then serve home
3. not found use router

**Comment by domwong** [comment]
Closing as we deprioritise web things
