### ISSUE TITLE
service.mu definition (drop proto)

### ISSUE THREAD

**Issue by asim** [micro/development#21]
Define a service.micro or service.mu file.

```
service {
        name: "status",
        metadata: { "namespace": "go.micro.srv" }
}

service.handle {
        "Get.Status": {
                id string,
        }
}

service.subscribe {
        topic: "status.updates",
}

service.debug = true
```

Drop in handlers and subscribers in any language.

**Comment by vtolstov** [comment]
i'm prefer yaml for definitions. this look mostly like hcl...

**Comment by asim** [comment]
We're not going to use yaml

**Comment by gedw99** [comment]
The defining of the subscribe within the proto is really exciting. 

When a client queries they also know where to subscribe for changes to the results of the query ? Is that the intent ? I have been building stuff this way also so its very easy for clients to interact with the system.

I use minio SQL Select with NATS. Its easy then to have many subscriptions held against an SQL query and then know when any data relating to a query has changed. Then you just publish a CUD event (Create, Update, Delete) back to the Clients. Its important its CUD because the clients can know react in the way that most suits them. 

Any way i am really interested to see the work being done here.

**Comment by asim** [comment]
The long term thinking is along the lines you're speaking of. We'll look to build a higher level "flow" abstraction that handles service-to-service calls and the various update mechanisms. This will be built into mu. Our starting point though is to be able to honour our client/server abstractions for request-response, streaming and pubsub. Proto does not allow us to do this. It also does not support our service abstraction or any of our abstractions for that matter. Protobuf is a good wire protocol but the proto IDL is bad for defining micro services.

This work will come together in the coming weeks as we start to prototype various ideas on paper. Our goal is to define a spec and then implement 3 programs on paper to see if this model fits.

**Comment by gedw99** [comment]
I also dumped proto and moved to openapi for the modelling of the users / developers API.
You can do runtime reflection or codegen and so runtime gives you is too like gateway at L4.
You are transport dependent.

Grpc is used with gnostic for internal flows.

The kin openapi golang implementation is ok.

But it's all

**Comment by asim** [comment]
Still on the roadmap but likely a 2021 thing
