### ISSUE TITLE
micro run <url> - k8s

### ISSUE THREAD

**Issue by domwong** [micro/development#229]
Add support for `micro run <url>` 

Suggested implementation is to have a generic go container which will do `go run` on the provided URL. This will provide us the most consistent experience relative to the local machine experience.

**Comment by asim** [comment]
Back in Feb we were doing this fairly successfully. 

micro run helloworld - would be relative to micro/services and run micro/services/helloworld
micro run github.com/foobar/baz - would run this specific repo
micro run . - would try to figure it out from the local dir

This entrypoint.sh script would do a sparse checkout of the code and just do `go run`.
https://github.com/micro/services/blob/master/entrypoint.sh. The image we used this with exists here https://hub.docker.com/r/micro/services.

Stealing from docker run and go run is useful. Just calling go run in the container is also good because if the source does not exist it will pull it. We used go athens proxy to cache go modules locally to speed up builds. 

The kubernetes runtime defaults a micro/go-micro default image in the deployment where none is specified https://github.com/micro/go-micro/blob/master/util/kubernetes/client/client.go#L26 and https://github.com/micro/go-micro/blob/master/util/kubernetes/client/client.go#L318. So worst comes to worst the default image contains the latest release of go-micro plus Go. 

Personally I feel like this was a solid starting point for running code. For some reason we moved to github actions on the assumption that running source code was slow but also compiling a go binary in a resource constrained container was an issue. I'm more inclined to think we can optimise later especially since what it buys is is the ability to run source from anywhere without dealing with builds. If we need to do containers, we create a build service that has higher resources and can pre-build on the fly.
