### ISSUE TITLE
can we provide an empty registry ?

### ISSUE THREAD

**Issue by crazybber** [micro/development#39]
in k8s ,many team don't need a  real function registry plugin  .

**Comment by asim** [comment]
Default registry does not have any dependency so should not be an issue to run in kubernetes. Memory registry also exists.

**Comment by vtolstov** [comment]
Yes, +1 for memory registry under k8s

пт, 10 янв. 2020 г., 11:39 Asim Aslam <notifications@github.com>:

**Comment by crazybber** [comment]
memory still needs to handle something.

**Comment by asim** [comment]
You're trying to remove a piece of functionality that's literally core to the way the framework works. If you want to do that, write a different client and server that totally ignores the registry. Otherwise the memory registry is a zero cost operation considering its entirely local to the process. It continues to enable the functionality in a closed loop.

**Comment by vtolstov** [comment]
If i have some free time i think that i can create noop registry, that not stores anything and only satisfies registry interface
