### ISSUE TITLE
web.micro.mu/account/ is blank

### ISSUE THREAD

**Issue by asim** [micro/development#91]
I guess we have an issue with handling subdomains and internal /account. What's the right way to deal with this? 

https://web.micro.mu/account/

**Comment by ben-toogood** [comment]
The issue is that the webapp is designed to be served at the root path. It does all the navigation using the URL path. I tried implementing it to work for both but I couldn't find an elegant solution. I feel like micro shouldn't put this complexity onto the service, and rather handle it in micro web. 

I want to look at adding SPA to micro web as a higher level thing, and possibly address this issue then?

**Comment by asim** [comment]
Makes sense. For the time being we need to decide how to properly solve this. Should we just be rendering subdomain links when resolver is set to subdomain?

**Comment by ben-toogood** [comment]
I think this makes sense, but we'll need to point *.micro.mu to the loadbalancer.

**Comment by ben-toogood** [comment]
https://github.com/micro/micro/pull/796
